config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups
  root 'groups#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path , notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:alert] = "Group deleted"
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:title, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:warning] = "早安！你好！"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
       <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div class="container text-center">
    <span class="text-muted">
      Copyright ©2020 Rails101
      <br> Design by 
      <a href="https://hackmd.io/XZtBIUtNSluYgVcuTBK1ZA" target="_blank">hihi</a>
    </span>
  </div>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Rails 101</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to("登入", '#', class: "nav-link") %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
  <div class="form-group">
      <%= f.input :title, input_html: { class: "form-control" } %>
      <%= f.input :description, input_html: { class: "form-control" } %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" , data: { disable_with: "Submiting.." }%>
<% end %>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>編輯討論版</h2>
  <hr>
  <%= render "form" %>
</div>

app/views/groups/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("New Group", new_group_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-haver">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Description</td>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td>#</td>
          <td><%= link_to(group.title, group_path(group)) %></td>
          <td><%= group.description %></td>
          <td>
            <%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default") %>
            <%= link_to("Delete", group_path(group), class:" btn btn-sm btn-default", method: :delete,
            data: {confirm: "Are you sure ?"}) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>新增討論版</h2>
  <hr>
  <%= render "form" %>
</div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("Edit", edit_group_path(@group), class: "btn btn-primary pull-right")%>
  </div>
  <h2><%= @group.title %></h2>
  <p><%= @group.description%></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Rails101</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column h-100">
    <header>
      <%= render "common/navbar" %>
    </header>
    <main role="main" class="flex-shrink-0 mt-5 pt-3">
      <div class="container">
        <%= render "common/flashes" %>
        <%= yield %>
      </div>
    </main>
    <footer>
      <%= render "common/footer" %>
    </footer>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello World</h1>